# Generated by Django 3.1.7 on 2023-03-04 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutPills', '0002_solution'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pills',
            fields=[
                ('seq', models.CharField(blank=True, max_length=30, null=True)),
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('company', models.CharField(blank=True, max_length=30, null=True)),
                ('detail', models.CharField(blank=True, max_length=10000, null=True)),
                ('shape', models.CharField(blank=True, max_length=15, null=True)),
                ('color', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'pills',
                'managed': False,
            },
        ),
    ]
