# Generated by Django 3.1.7 on 2023-03-11 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutPills', '0004_member_zzim'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('uid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'likes',
                'managed': False,
            },
        ),
    ]
