# Generated by Django 3.1.7 on 2023-03-12 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutPills', '0006_auto_20230311_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='PillsLikes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('seq', models.CharField(blank=True, max_length=30, null=True)),
                ('name', models.CharField(max_length=50)),
                ('company', models.CharField(blank=True, max_length=30, null=True)),
                ('detail', models.CharField(blank=True, max_length=10000, null=True)),
                ('shape', models.CharField(blank=True, max_length=15, null=True)),
                ('color', models.CharField(blank=True, max_length=15, null=True)),
                ('image', models.CharField(blank=True, max_length=1000, null=True)),
                ('zzim', models.BooleanField(default=False)),
                ('printing', models.CharField(blank=True, max_length=20, null=True)),
                ('uid', models.CharField(max_length=20)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
